name: Run Airline Price Tracker

on:
  schedule:
    - cron: '0 0 * * 5'  # This cron expression schedules the job to run on Friday at midnight UTC
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python cheapestOneWay.py

    - name: Upload CSV files
      uses: actions/upload-artifact@v4
      with:
        name: csv-files
        path: results/departures/*.csv